### ISSUE TITLE
Any plan for adding subtitles ?

### ISSUE THREAD

**Issue by bekicot** [amilajack/popcorn-time-desktop#105]
On MacOs Sierra, the official popcorn time doesn't work. This fork is working and starting to have faith on it, since the original popcorn time using custom made NWjs which is seem buggy on Sierra. 
I guess this version of popcorn time will be a good alternative.

Anyway. Any plan for adding subtitle support ?

**Comment by amilajack** [comment]
This is not a fork of the original popcorn-time client. It is a from-scratch implementation.

And yes, subtitles are in the roadmap: https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress

**Comment by amilajack** [comment]
I'm also looking for testers. Please let me know if you are interested.

**Comment by bekicot** [comment]
Oh, my apology for not doing research.
I did testing it, and I say it is working for searching and streaming.
Let me know if you need more output / logs. Just guide me how to get it.

**Comment by amilajack** [comment]
Definitely. Also it would be nice if you could help spread the word about this client. I'm actively working to find more developers to collaborate.

**Comment by amilajack** [comment]
Also I have a few questions:
1. Did you build the app from source or are you using the precompiled app?
2. What are the differences that you noticed between this app and the official client?

**Comment by bekicot** [comment]
Already did on reddit. Anyway, I also developer, but more on backend Ruby on Rails, I do also front end.
Clone and building it. Just before you commented. :)
I was using the prebuilt binary.

**Comment by amilajack** [comment]
Thanks! Also

> What are the differences that you noticed between this app and the official client?

**Comment by bekicot** [comment]
It is different. 
The build prosess is not complete. Been 2 hours now

**Comment by amilajack** [comment]
1. What steps did you take to build?
2. What machine are you using? (Macbook Pro 2015, etc)
3. Is there a specific part of the install process that is slow?
4. What is your node and npm version?

**Comment by bekicot** [comment]
I did the steps shown on the readme. 
```
git clone https://github.com/amilajack/popcorn-time-desktop.git
cd popcorn-time-desktop


# Install all the dependencies
# Remember to `npm rebuild` if necessary
npm install

# Dev build
npm run dev

# Prod build
npm run package

# If you hit the 'Failed to load resource' error (found in the console), refresh Electron (CMD/ctrl + R)
# This is caused when Electron is trying to fetch the compiled file before it has finished.
```

2. Mac Book pro 2015, sierra, NVM as node version manager
3.  Both when running `npm run dev` or `npm run package`
4. Node `v6.2.2`; Npm `3.10.6`

**Comment by amilajack** [comment]
`npm run dev` or `npm run package` generally take a long time because they compile all of our node_modules into one file (extremely computationally expensive since we have a lot of dependencies). Furthermore, all of our project's modules need to be transpiled to es5, which takes some time. `npm run package` also takes a lot of time because, while having the responsibility to bundle all our code, it also performs performance optimizations.

**Comment by amilajack** [comment]
Initial working prototype:

https://drive.google.com/file/d/0B62q4hLyBtKbV2V2LVZDNFlPQ1k/view?usp=sharing

**Comment by amilajack** [comment]
@bekicot Subtitles are now behind a flag. You can now checkout the `release-0.0.5-alpha` branch and set a build flag like so: 

```
FLAG_SUBTITLES=true npm run package
```
