### ISSUE TITLE
Parallelize mocha tests

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#112]

**Comment by amilajack** [comment]
https://github.com/mmotkina/mocha-parallel-tests/issues/53

**Comment by thangngoc89** [comment]
I usually use AVA. It was built with parralism and es6 in mind

**Comment by amilajack** [comment]
Initially, this project was using Ava but I had to switch to mocha because I couldn't get chaijs to work with mocha

**Comment by amilajack** [comment]
I also like the cleaner output of mocha.

**Comment by amilajack** [comment]
But if we can get these things with Ava, lets migrate to it.

**Comment by thangngoc89** [comment]
Ok. That's cool. Can you be more specific sbot what you can't do with ava?

**Comment by amilajack** [comment]
It's helpful to have the tests output in a 'list', like they do in mocha.

**Comment by thangngoc89** [comment]
I played around with Jest for a few day. So far so good, it uses expect as it assert library so no change on tests file. And with Jest 14, they  released a killer feature: Snapshot testing with React 

http://facebook.github.io/jest/blog/2016/07/27/jest-14.html

I suggest you give it a try

**Comment by amilajack** [comment]
This should be a planned feature but at the moment i dont think its very urgent. When this project is stable i think we should migrate add screenshot tests to all the component tests.

**Comment by thangngoc89** [comment]
> we should migrate add screenshot tests to all the component tests.

Agreed. Visual testing is slow and error prone.

I forgot to mention, Jest can run test in parallel by default

**Comment by onbjerg** [comment]
@amilajack You can get mocha-like output from ava. Remember that ava is TAP-compatible, so you can [use](https://github.com/scottcorgan/tap-dot) [any](https://github.com/calvinmetcalf/tap-nyan) [TAP](https://github.com/gummesson/tap-min) [reporter](https://github.com/zoubin/tap-summary).

[This](https://github.com/tapjs/tap-mocha-reporter) was probably the one you were looking for.

**Comment by amilajack** [comment]
@onbjerg Can I have nested tests like this:

```
describe('Some', () => {
  describe('Another', () => {
    it('should test Foo', () => {
      // Some test here
    })
  })
})
```

**Comment by onbjerg** [comment]
Not really. I agree with sindre that it is sort of an anti-pattern and should be discouraged. The most you can do is:

```js
import test from 'ava'

test('something', (t) => {
  t.is(1, 1, '1 is 1')
})
```

Regardless, the thing you're asking was/is being discussed in avajs/ava#222.

**Comment by amilajack** [comment]
Can chai be used with ava?

**Comment by onbjerg** [comment]
Actually, scratch that. There's a package for that(tm): https://github.com/sheerun/ava-spec.

>Can chai be used with ava?

Yes. But you might want to read a bit more about it here, as there are some trade-offs: [Custom assertions](https://github.com/avajs/ava#custom-assertions).

**Comment by amilajack** [comment]
I see. All our tests are already written in mocha. It would be worth he migration to ava if it supported running tests on multiple threads. At the moment tho there are a bunch of architectural concerns with the project. Are you interested in contributing? 😁

**Comment by onbjerg** [comment]
It runs tests in parallel per default.

I am up for contributing 🍇

**Comment by amilajack** [comment]
Yesss! 🔥🎉😁

What areas are you experienced in? Node? React? Redux? etc

**Comment by onbjerg** [comment]
Been doing Node for a few years, been doing React/Redux for a year or so 😬  I'm experienced in a lot of other things, too, but I don't think they apply to this project.

**Comment by amilajack** [comment]
That's great! Also I invited you to the gitter. I just commented an [introduction to the project](https://gitter.im/amilajack/popcorn-time-desktop?at=58025b9978bd0d0363c70de8). Would recommend checking that out.

**Comment by amilajack** [comment]
@onbjerg just looked into jest and it looks very promising. What do you think about PR'ing for this? 😀
