### ISSUE TITLE
Add Zooqle provider

### ISSUE THREAD

**Issue by ZakariaRidouh** [amilajack/popcorn-time-desktop#114]
we can use this thread for discussion

**Comment by amilajack** [comment]
Lets also add EZTV to the discussion as well

**Comment by amilajack** [comment]
@thangngoc89

**Comment by ZakariaRidouh** [comment]
Alright, so are there any existing EZTV scrapers out there? IIRC the old popcorntime.io use to use EZTV for TV Shows.

**Comment by amilajack** [comment]
Actually now that I think about it eztv isn't that good of an idea since the website doesnt show the seeder count. We could determine that at runtime but that would be costly. I'll look into how existing strem.io providers are doing this

**Comment by thangngoc89** [comment]
There is yts and seztv available in strem.io. We can use it instead.

**Comment by thangngoc89** [comment]
As far as I know, eztv is the best source for tv shows

**Comment by ZakariaRidouh** [comment]
Is there anything that can be salvaged from the old popcorntime eztv TV show scrapper?

**Comment by amilajack** [comment]
Is there a way to get the seeder count of the torrents on eztv?

**Comment by ZakariaRidouh** [comment]
![image](https://cloud.githubusercontent.com/assets/11602629/17312610/c157c394-5808-11e6-9ba2-1f53f62529bf.png)
Hmm, seems like the 'Alternate Releases' section shows the seeders and leechers for the alternate episode meaning they are recorded. Ill do some more digging to see if it shows up anywhere else.

**Comment by amilajack** [comment]
This means that the crawler/scraper would have to navigate to each link and scrape each page (at runtime). This would lead to a suboptimal experience. In strem.io's case, they're doing this on the server, according to @thangngoc89. We could find a way to make requests to their servers.

**Comment by thangngoc89** [comment]
> We could find a way to make requests to their servers.

It's well documented here. https://github.com/Stremio/stremio-addons

About EZTV and YTS, there is Popcorn times plugin that fetch content from thoes sites https://github.com/JCB9090/pct-addon

You can spawn a instance of it locally or use a hosted version of it

**Comment by thangngoc89** [comment]
Well, looks like pct addon is just a wrapper of official popcorn-api https://github.com/popcorn-official/popcorn-api

**Comment by ZakariaRidouh** [comment]
https://github.com/ChrisAlderson/eztv-api-pt

Looks like thats what we're looking for.

**Comment by amilajack** [comment]
[https://zooqle.com](https://zooqle.com/) is a provider I think we might be interested in.

**Comment by ZakariaRidouh** [comment]
@amilajack *and*, it looks like they have a nice API https://zooqle.com/help/api.html

**Comment by amilajack** [comment]
@ZakariaRidouh is it possible to query using an imdb id?

**Comment by amilajack** [comment]
I looked more into zooqle and I found that their seeder counts dont really beat ours. Let me know if you think otherwise.
