### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by mswahmedabad** [amilajack/popcorn-time-desktop#121]
I can't find any option to add subtitles. Drag/Drop subtitle file is also not working. (I am on 16A254g)

**Comment by amilajack** [comment]
This is an upcoming feature of this project:

https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress#planned-featuresimplementationsmigrations

You can 'watch' this repo to follow our progress.

**Comment by mswahmedabad** [comment]
Where is 'cache' folder located in this version?

**Comment by amilajack** [comment]
it should be saved in ./tmp/webtorrent

**Comment by amilajack** [comment]
Eventually this will be configurable through an env variable and the UI

**Comment by mswahmedabad** [comment]
Okay, thanks.

**Comment by iamDeveloper** [comment]
Hey! I can't find the cache in ./tmp/webtorrent
