### ISSUE TITLE
Many images causing slow scroll performance

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#13]
Retaining all the images that have been loaded into the application can have significant performance implications. Setting the src attribute of an `img` element to a `#` may be enough to garbage collect it:

``` js
document.getElementById('img').src = "#";
```

**Comment by thangngoc89** [comment]
Maybe using some special technique like destroy DOM after scroll past it. 

https://github.com/jwarning/react-scrollable-list

**Comment by amilajack** [comment]
Really nice! Thanks!

**Comment by amilajack** [comment]
@thangngoc89 wondering if you can make a PR for this?

**Comment by thangngoc89** [comment]
https://github.com/bvaughn/react-virtualized

**Comment by amilajack** [comment]
Wow. Even better!

**Comment by amilajack** [comment]
Wasted a bunch of time on twitter and I found this:

https://twitter.com/paul_irish/status/755107282917076992

Could help us.

**Comment by thangngoc89** [comment]
an implementation: https://elements.polymer-project.org/elements/iron-list

**Comment by amilajack** [comment]
Should check out [this thread](https://github.com/bvaughn/react-virtualized/issues/368#issuecomment-243468736).
