### ISSUE TITLE
Multi-lang subtitles

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#136]
Currently, this feature doesn't work correctly. It fetches subtitles for the correct show/movie but it retrieves subtitles with different starting times. This means that movies and subtitles are usually out of sync.

Waiting on https://github.com/vankasteelj/opensubtitles-api/issues/16

**Comment by vzamanillo** [comment]
Other applications (like strem.io) are offering the possibility to increase or decrease the subtitle speed to sync with the movie (that's enought if the subtitle out of sync is by milliseconds), or showing a link or button with "wrong subtitles?" and then shows a popup to change the subtitle provider file for your language.

**Comment by amilajack** [comment]
That's a very interesting approach. I wonder how they're doing that. I'll look into it.

**Comment by vzamanillo** [comment]
What subtitle provider are you actually using? I am looking for the API provider but can't find it.

**Comment by amilajack** [comment]
I'm using the opensubtitles api in [this branch](https://github.com/amilajack/popcorn-time-desktop/tree/subtitles-support)

**Comment by vzamanillo** [comment]
I will take a look, thank you.
