### ISSUE TITLE
Screen Alignment 

### ISSUE THREAD

**Issue by iamDeveloper** [amilajack/popcorn-time-desktop#139]
The cover is not aligned in center. It comes in center in few movies but mostly not. Its uncomfortable to watch like this. Can we make it better?

![popcorntime - popcorn time - screen shot 18-aug-2016 1 11 50 am](https://cloud.githubusercontent.com/assets/2689724/17750829/08dae026-64e2-11e6-9d21-0e9f908e2e04.png)

Thankyou

**Comment by amilajack** [comment]
What release or branch are you using?

**Comment by iamDeveloper** [comment]
0.0.4

**Comment by amilajack** [comment]
That bug is fixed in release 0.0.5. You can either download the build from the releases or checkout release-0.0.5-alpha branch
