### ISSUE TITLE
Migrate towards webpack 2

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#141]
These are good blog posts outlining a migration path to webpack 2:

https://blog.engineyard.com/2016/tree-shaking
https://gist.github.com/nikolasleblanc/b7680bfa8aa007fd84ffc8a32db613ea

**Comment by thangngoc89** [comment]
It's pretty straight-forward. See https://github.com/facebookincubator/create-react-app/pull/189

**Comment by amilajack** [comment]
Is it stable?

**Comment by thangngoc89** [comment]
Nope. But I used it in production for a while now without any issues.
