### ISSUE TITLE
Posterholder can not be resolved when no card image

### ISSUE THREAD

**Issue by vzamanillo** [amilajack/popcorn-time-desktop#149]
Trys to resolve 

`file:///C:/desarrollo/GitWorkspace/images/posterholder.png`

 the correct path should be

`file:///C:/desarrollo/GitWorkspace/popcorn-time-desktop/app/images/posterholder.png`

![posterholder issue](https://cloud.githubusercontent.com/assets/10209695/17939891/c74979f6-6a2c-11e6-8e30-5a55e3c70054.png)

**Comment by amilajack** [comment]
@ZakariaRidouh can you look into this? If I remember correctly, a PR you made changed this.

**Comment by amilajack** [comment]
@vzamanillo a PR fixing this would be welcome!

**Comment by vzamanillo** [comment]
I am working on it :)

**Comment by ZakariaRidouh** [comment]
@amilajack @vramana the local poster is here: `popcorn-time-desktop/app/images/posterholder.png`

**Comment by amilajack** [comment]
Was this fixed?

**Comment by vzamanillo** [comment]
Yep.

**Comment by amilajack** [comment]
Thanks!
