### ISSUE TITLE
Target Preact in Production

### ISSUE THREAD

**Issue by ZakariaRidouh** [amilajack/popcorn-time-desktop#152]
I tried working on this and using [`preact-compat`](https://github.com/developit/preact-compat) but every time the app runs, this error appears: 
![14030687_1009052909214714_379107144_n](https://cloud.githubusercontent.com/assets/11602629/17947547/fea89c2c-6a01-11e6-998c-2d323de61d63.png)

**Comment by amilajack** [comment]
Is there a branch that we cans test out?

**Comment by ZakariaRidouh** [comment]
@amilajack: yep, https://github.com/ZakariaRidouh/popcorn-time-desktop/tree/preact

**Comment by amilajack** [comment]
Try adding back the `react` dep.

**Comment by amilajack** [comment]
I've got it to work in development but in production I'm getting errors:

```
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactTransitionGroup' in ./react-addons-transition-group
```

This can be solved by: https://github.com/developit/preact-compat/issues/14#issuecomment-193358030

but `rc-css-transition-group` has been deprecated. Migration to preact isn't worth migrating to deprecated modules.

**Comment by thangngoc89** [comment]
Well, unless there is a standalone ReactCSSTransitionGroup package, migrating to preact-css doesn't worth it. And most of an electron app size comes from electron itself, not the js app
