### ISSUE TITLE
Cannot 'npm run dev'

### ISSUE THREAD

**Issue by TriPSs** [amilajack/popcorn-time-desktop#158]
When the electron application starts i get a 404 not found for bundle.js

I'm using Windows 10 and Node version 6.5

**Comment by amilajack** [comment]
try this:

```
rm -rf node_modules      # idk if you can do this on windows but just delete the node_modules dir
npm cache clean
npm i
npm rb
npm run dev
```

**Comment by TriPSs** [comment]
Yes, thats the first error i get after that i did indeed refresh the page.

On my Windows machine i use cygwin so all the linux commands are available ;)

Gone try this again when i'm home, will give an update then.

**Comment by TriPSs** [comment]
Got it working on my Mac, had the same error there so i think it wil work nog on my Windows to.

Thanks! Looking forward to start working on this project.

**Comment by TriPSs** [comment]
Got a couple of questions:

Why this:
![image](https://cloud.githubusercontent.com/assets/7668692/18341280/91e0bb48-75a9-11e6-9d38-91767eeb5cdb.png)

And not this:
![image](https://cloud.githubusercontent.com/assets/7668692/18341260/81bc2626-75a9-11e6-8e42-4aec8a310281.png)

And same for props, binding of the functions will then be done in the constructor.

**Comment by amilajack** [comment]
Oh right! Can you make a PR for that?

**Comment by TriPSs** [comment]
I will walk true all the code this evening/tomorrow, after that i will create a PR for you.

**Comment by amilajack** [comment]
Closing, as I think this issue has been resolved.

**Comment by vaibhavpacharya** [comment]
"Not rewriting GET /dist/bundle.js because the path includes a dot (.) character." 
This is my error for the same problem above. I followed all your instructions, but this error keeps getting on.
Please help
