### ISSUE TITLE
Broken design

### ISSUE THREAD

**Issue by juanscv** [amilajack/popcorn-time-desktop#166]
Design seems to be broken, compared to the images shown here.

http://take.ms/ETMsv

- PT 0.0.5-alpha
- Mac OS Sierra Golden Master

**Comment by ZakariaRidouh** [comment]
@juanscv The designs have not been implemented yet, that's what is being worked on currently in release 0.0.6.

You can look at the [Roadmap & Progress](https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress) here.

😸

**Comment by amilajack** [comment]
https://github.com/amilajack/popcorn-time-desktop/issues/18

😂 Throw back
