### ISSUE TITLE
Not listing first season on sidebar

### ISSUE THREAD

**Issue by juanscv** [amilajack/popcorn-time-desktop#168]
Sometimes a show with multiple seasons, the first season's episode list loads but you can't see a link for season 1 on the sidebar, only season 2 and next.

PT 0.0.5-alpha
Mac OS Sierra Golden Master

**Comment by amilajack** [comment]
We get all out information about tv shows and movies from Trakt's API. For some shows, Trakt returns all the seasons but the first. Its pretty odd why. But in comparison to the original pct client, I think it performs much better (at least in seeder count).

**Comment by amilajack** [comment]
On a side note, have you noticed any performance differences between this client and others?

**Comment by juanscv** [comment]
My example is Blindspot. It does have Season 1 episodes, so we should check if the episodes are there, and then add it. I assume the api returns for each episode season and episode number (season: 1, episode: 22)

**Comment by amilajack** [comment]
The API returns all the seasons for a given show. So requesting a show with a given imdbId will return all its seasons
