### ISSUE TITLE
PR: "No Internet connection available" notification

### ISSUE THREAD

**Issue by karuppiah7890** [amilajack/popcorn-time-desktop#173]
@amilajack 

When I switched off Internet, and opened up the application, it just shows the loading symbol. No notification saying that it was unable to connect to the Internet. 

Same thing happens if I switch off the Internet while using the application. I try to scroll, and it just shows that it's loading and it goes on infinitely. No notification of "No Internet connectivity".

I think there should be some notification saying that there are some Internet connectivity issues.

**Comment by amilajack** [comment]
Thanks for opening this issue! It would be great if you could make a PR for this.

**Comment by ZakariaRidouh** [comment]
@karuppiah7890 Are you talking about the notification popping up in any part of the UI or just while playing a movie/consuming bandwidth?

Cheers!

**Comment by amilajack** [comment]
Ideally errors would be shown within the app itself. Notifications would be ideal for when events like progress completion of torrent downloads.

**Comment by karuppiah7890** [comment]
@ZakariaRidouh I didn't get you. And I am talking about getting notifications within the App UI. And it should be pop up anytime the App detects no Internet connectivity. And @amilajack yes, you are right, showing a notification through the OS notification service should be great for special events. And errors can be show within the App so that the user understands the error based on the context of the page where the error is shown.

**Comment by karuppiah7890** [comment]
@amilajack Yeah, I will check on the notification code and get back!

**Comment by ZakariaRidouh** [comment]
@karuppiah7890 What I was attempting to say is whether the alerts would pop up even if you're in the settings page of the app or in the card view, or would it only show up when you're watching a TV show or Movie.

thanks

**Comment by karuppiah7890** [comment]
I am sorry for being idle about this issue. I couldn't get the dev build working, so couldn't code properly.

And @ZakariaRidouh I was talking about showing notifications, whenever there is some loader shown to the user. Even in the card view, when the user scrolls to the end to see more movies, if the Internet is connected, it shouldn't load infinitely. And should show an error notification instead. Even when the app starts, if the Internet is not connected due to some issues ( say some IP problems or proxy stuff or something ) then the App shouldn't load infinitely showing the loading symbols and should instead show an error notification after a timeout, asking the user to check for Internet connectivity.

@amilajack The issue isn't solved right ? Why close ? You wanna take care of this later ?

**Comment by amilajack** [comment]
> The issue isn't solved right ? Why close ? You wanna take care of this later?

My bad. I confused this with the other issue that you made and said you would make a PR for a fix. This should be open.

**Comment by amilajack** [comment]
I changed to title of this issue to make finding possible PR's easier.

**Comment by karuppiah7890** [comment]
Sure!

**Comment by amilajack** [comment]
Fixed this in `v1.2.0`
