### ISSUE TITLE
No 0.0.6 alpha release for Debian Distributions ? :/

### ISSUE THREAD

**Issue by karuppiah7890** [amilajack/popcorn-time-desktop#174]
@amilajack 
I use Ubuntu. I was checking for .deb files in the latest release and couldn't find one. Can you please build it for Debian Distributions too ?

**Comment by amilajack** [comment]
Actually I'm thinking of taking down 0.0.6 because it's not finished yet

**Comment by karuppiah7890** [comment]
Thanks for the info! 

I was actually surprised when git actually didn't show me any branch other than master when I did `git branch`, but looks like it detects them only when I check them out using `git checkout branch_name`. I will build it and check it out! :smile:

**Comment by amilajack** [comment]
The reason why its difficult for me to build for all environments at once is because the app has native deps. Currently I have to manually compile on each machine and upload to github 😢

**Comment by karuppiah7890** [comment]
Oh. Just get some more people, say moderators, to compile for different machines. Choose them such that they use that corresponding machine extensively.

**Comment by amilajack** [comment]
The proper way of doing this is using travis and appveyor artifacts. Haven't had the time to implement them yet :(

**Comment by karuppiah7890** [comment]
Oh okay..
