### ISSUE TITLE
Development Issue : Not able to fetch torrents while using development build

### ISSUE THREAD

**Issue by karuppiah7890** [amilajack/popcorn-time-desktop#175]
@amilajack Hey, I got the App's src files and npm packages and modified some source code and finally did 

`npm run dev`

and was trying to watch a movie. But all it said was "Fetching torrents". Later, I discarded all my changes and tried it all again and still wasn't able to get the torrents loaded. 

I was confused, and then I deleted everything and got all the src files again from scratch and redid everything. Still wasn't able to load the torrents. Finally to be sure, I packaged the App using 

`npm run package`

and it packaged the App in the `releases` directory and when I run the packaged App, I am able to fetch the torrents and the "Start 720p" and other buttons get enabled. I am pretty confused now.

What have I done wrong ? Is it something about the `.env` file ? But I just copied it from the `.env.example` file and never changed it. And I think it looks fine.

And when I do API tests using `npm run test-api`, a lot of tests are failing, including "getting torrents and their magnets for 720p and 1080p" test. I am attaching the images of the test over here.

Image 1 : 
![1](https://cloud.githubusercontent.com/assets/12808424/19211360/296d17fc-8d58-11e6-9c47-82cb12b8e1ef.png)

Image 2 : 
![2](https://cloud.githubusercontent.com/assets/12808424/19211381/8251c4d0-8d58-11e6-9f5b-d0940c1bf0d1.png)

Image 3 : 
![3](https://cloud.githubusercontent.com/assets/12808424/19211384/89b5256e-8d58-11e6-8f17-9149b3f8a177.png)

Image 4 : 
![4](https://cloud.githubusercontent.com/assets/12808424/19211386/91d9bc64-8d58-11e6-9ee8-aaf1a31596fb.png)

Image 5 : 
![5](https://cloud.githubusercontent.com/assets/12808424/19211390/a16cf36c-8d58-11e6-8948-bf7afb2105b4.png)

Please do help me with this!

**Comment by amilajack** [comment]
Here's why the tests are failing:

1. `Expected 300 to be above 400`: This is failing because the torrent provider isnt returning the optimal amount of seeders. Obviously the seeder counts of torrents change over time so testing against this was somewhat unusual but I wanted to assert somehow that we were retrieving an optimal amount of seeders for each provider. For example, if I make a change to a provider, i dont want the seeders to suddenly go from ~400 to 100.

2. `Timeout exceeded`: This is failing probably because the endpoint is either blocked or the provider's endpoint is down. This this is one of the most common reasons for test failure.

3, 4. `Expected undefined to be a string`: I just noticed this on my build today as well. I made the tests even stricter and fixed the issue causing this 😄 

Please lmk if you have any more questions!

**Comment by karuppiah7890** [comment]
And what about the torrents not fetching in development build ? But when I
package and use the App, the torrent is fetched.

**Comment by amilajack** [comment]
What errors are you getting in the console?

**Comment by karuppiah7890** [comment]
That's the problem, I don't get any errors in the developer tools. But just
now I got an error when i tried some totally new movie, and it said said
some "Type error" and said "Can't write to a read only object".

**Comment by karuppiah7890** [comment]
I get this : 

Movie.js:559 
>TypeError: Cannot assign to read only property '0' of object '[object Array]'
>    at Array.sort (native)
>    at sortTorrentsBySeeders (webpack:///./app/api/torrents/BaseTorrentProvider.js?:278:19)
>    at selectTorrents (webpack:///./app/api/torrents/TorrentAdapter.js?:272:71)
>    at _callee$ (webpack:///./app/api/torrents/TorrentAdapter.js?:116:28)
>    at tryCatch (webpack:///./~/regenerator-runtime/runtime.js?:62:40)
>    at GeneratorFunctionPrototype.invoke [as _invoke] (webpack:///./~/regenerator-runtime/runtime.js?:336:22)
>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (webpack:///./~/regenerator-runtime/runtime.js?:95:21)
>    at tryCatch (webpack:///./~/regenerator-runtime/runtime.js?:62:40)
>   at GeneratorFunctionPrototype.invoke [as _invoke] (webpack:///./~/regenerator-runtime/runtime.js?:278:24)
>    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (webpack:///./~/regenerator-runtime/runtime.js?:95:21)
>    at step (webpack:///./~/babel-runtime/helpers/asyncToGenerator.js?:17:30)
>    at eval (webpack:///./~/babel-runtime/helpers/asyncToGenerator.js?:28:20)

Image : 

![error](https://cloud.githubusercontent.com/assets/12808424/19214721/b641027a-8da7-11e6-82d1-56262854e0c4.png)

**Comment by amilajack** [comment]
Hmm. That's weird. Are you sure you have the most recent changes of `ui-design-implementation` branch?

**Comment by amilajack** [comment]
Oh wait you arent on that branch at all. [Here's the steps for building](https://github.com/amilajack/popcorn-time-desktop/issues/174#issuecomment-252297436) in case you missed them. I can't guarantee any other branch works properly.

**Comment by amilajack** [comment]
Update: I've just merged the `ui-design-implementation` branch into the `release-0.0.6-alpha` branch. You don't have to switch branches but you should if you want to receive updates in the future.

```
release-x.x.x-alpha => dev-master => master
```

**Comment by karuppiah7890** [comment]
@amilajack I am sorry for bothering you so much for this issue.

And yeah, I get it that I should use the `ui-design-implementation` branch to get new updates. But I am on the `master` branch, which I believe is stable, and I have packaged the App using `npm run package` in the `master` branch and everything works fine in the packaged App, including the fetching of torrents and showing the movie. But when I use the development build using `npm run dev` on the `master` branch, I am not able to fetch torrents and not able to see any movie. Why is this so ? It's absurd.

**Comment by amilajack** [comment]
> And if I want to make a pull request, should it be pointed to the master branch or dev-master or release-x.x.x-alpha or what ?

All PR's should be made to `release-x.x.x-alpha`

> But I am on the master branch, which I believe is stable

Unfortunately it isnt. Both travis and appveyor builds are failing on it:

<img width="416" alt="screen shot 2016-10-08 at 10 50 02 pm" src="https://cloud.githubusercontent.com/assets/6374832/19218231/91a7b3ee-8da9-11e6-8e3d-53773a7314ef.png">

Currently `release-0.0.6-alpha` is the most stable.

**Comment by karuppiah7890** [comment]
Damn. Then how is my packaged App alone working ? It was packaged using `master` branch code

**Comment by karuppiah7890** [comment]
And yeah, I will get the `release-x.x.x-alpha` code. And can we please make all this clear in the CONTRIBUTE.md ? Helps newbies like me, who didn't notice the build badges. And it will help others to know which branch to contribute to.

**Comment by amilajack** [comment]
Webpack has separate build steps for production and development environments. dev env is significantly slower and has much more deps. production webpack config strips everything out and optimizes js as much as it can.

**Comment by karuppiah7890** [comment]
Oh, okay. Thanks for the info. I guess I will just use the `release-x.x.x-alpha` branch

**Comment by amilajack** [comment]
>  And can we please make all this clear in the CONTRIBUTE.md

This is definitely a good idea. This would clear up so much unnecessary confusion. Sorry about that! I have a number of weird conventions for this project but I think they'll pay off in the end. The reason why there's a `release-x.x.x-alpha` branch is so that all the members of the team know what is the latest release. Also if we want to patch an old release, we can do that. Also if you haven't seen it yet, [here's the roadmap](https://github.com/amilajack/popcorn-time-desktop/wiki/Road-Map-and-Progress).

**Comment by amilajack** [comment]
Just added a [PR section](https://github.com/amilajack/popcorn-time-desktop/blob/master/CONTRIBUTING.md#pull-requests) to the CONTRIBUTING.md. Thanks for the suggestion!

**Comment by amilajack** [comment]
Let me know if the issue persists in that branch. If it does then I'll reopen the issue

**Comment by karuppiah7890** [comment]
No, the issue doesn't persist in the `release-0.0.6-alpha` branch

**Comment by karuppiah7890** [comment]
No, the issue doesn't persist in the `release-0.0.6-alpha` branch
