### ISSUE TITLE
Linux binary for latest release

### ISSUE THREAD

**Issue by dyskette** [amilajack/popcorn-time-desktop#178]
There is only a mac binary there. I tried to build linux x86_64 but failed miserably.

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Current node version is not supported for development, expected "4.5.0" to satisfy "6.x".
    at Object.<anonymous> (/tmp/popcorn-time-desktop/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

I'm guessing here that probably is the version of nodejs of my distro... but anyway, I'm just a simple user. So, could you please add some binary for linux x86_64?

**Comment by amilajack** [comment]
It failed because you need to be using at least node 6. If you upgrade it and follow these steps, you should be fine.

```bash
git clone https://github.com/amilajack/popcorn-time-desktop.git
cd popcorn-time-desktop

# Checkout the`release-0.0.6-alpha` branch
git checkout release-0.0.6-alpha

# Install dependencies
# Have a cup of coffee ☕️ this might take a while
# Remember to `npm rebuild` if necessary
npm install

# Customize Build
# Feel free to enable flags and configs in the `.env` file
vi .env

# Developement build
npm run dev

# Production build
npm run package
```
If you dont want to do that, that's fine! I understand how compiling can be a mess. I'll compile and upload it in a few minutes.

**Comment by amilajack** [comment]
Sorry for the wait. I'm trying to compile this on my linux machine, which has a dual core centrino @ 1.5ghz. Bear with me here! 😂

**Comment by amilajack** [comment]
Finally uploaded! It's the `.AppImage` file. Also I would recommend you only use this if you're in for some rough parts. This isnt a fully finished build. Use 0.0.5 if you want something more stable. 0.0.6 is strictly for people who want an early preview of this project.

**Comment by probonopd** [comment]
Thanks for the [AppImage](http://appimage.org/). Runs out-of-the-box on Ubuntu 16.04. 
But video cannot be made fullscreen.

**Comment by amilajack** [comment]
Try clicking on the video and pressing `f1

**Comment by probonopd** [comment]
Doesn't seem to work. There is a fullscreen button in the bottom-right of _some_ videos, but it seems to be cropped away for others.

**Comment by amilajack** [comment]
Would be much easier to debug if you could send a gif of a screen recording.
