### ISSUE TITLE
0.0.6: Can't click on other episodes

### ISSUE THREAD

**Issue by juanscv** [amilajack/popcorn-time-desktop#179]
I enter a show, click a different episode or season... nothing happens. I can't switch. The ep or season aren't clickable at all.

On latest 0.0.6 alpha
MacOS Sierra

**Comment by amilajack** [comment]
`0.0.6` is for testers only. It is not very stable at the moment. I would recommend `0.0.5` if you want something more stable. I'll look into why this isn't working. Also we currently don't have any tests for asserting episode/season functionality so a PR for them would be great!
