### ISSUE TITLE
Not able to see "Shows" section in Dev build and sometimes Tests for them behave strangely

### ISSUE THREAD

**Issue by karuppiah7890** [amilajack/popcorn-time-desktop#180]
I am in the `release-0.0.6-alpha` branch. I have built using it and I have noticed that the Tv Shows section wouldn't show up, instead only the Movies section would be visible even after clicking `Shows`. But when I did testing using `npm run test`, somehow my tests passed a few times, but a while ago they didn't pass. An error showed up and said the Shows section isn't shown, which is true.

And after trying the test  command a few more times, the tests finally started to pass and the Shows section actually showed up while doing `npm run test`.

What is this strange behavior ? And when I package the App, the Tv Shows section is visible perfectly. But that can possible because of Webpack's different environments for production and developement. 
But why does this strange behavior happen even within different tests on the Dev build ?

**Comment by amilajack** [comment]
Not sure why. There are a lot of bugs like that that have encouraged me to rewrite the entire `Item` module.

**Comment by karuppiah7890** [comment]
Oh, okay.

**Comment by karuppiah7890** [comment]
So, shall I close it ? Or you wanna close it when you push the code for all this ?

**Comment by amilajack** [comment]
Nah, keep it open. Its a good reminder. Lets close it when its fixed.

**Comment by karuppiah7890** [comment]
Ah, okay!
