### ISSUE TITLE
Add Issue and PR templates

### ISSUE THREAD

**Issue by karuppiah7890** [amilajack/popcorn-time-desktop#181]
I have contributed to FreeCodeCamp and they have a very nice [Issue](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/.github/ISSUE_TEMPLATE.md) and [PR](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6ce5f14e779673ae117de41c664fea6989750bc9/.github/PULL_REQUEST_TEMPLATE.md) templates. 

And when PRs are merged, the corresponding Issue mentioned in the template is closed. I don't know how it happens, but somewhere it was mentioned that GitHub does it automatically. Do check out about it. 

And Issue template is very useful. You can ask if the person is a user/tester/ developer and you can ask the version of the App he/she is using, for testers(or) the branch he/she is on, for developers and ask them the issue's description, their OS details and then may be even a screenshot. You can add more to the template. The above was was just a suggestion. And yeah, this will make the issue more elaborate and you won't have to ask redundant questions to the people who report the issues.

**Comment by ZakariaRidouh** [comment]
On it 😄

**Comment by karuppiah7890** [comment]
Nice! :smile:

**Comment by amilajack** [comment]
@karuppiah7890 Btw are you interested in being long term contributor?

**Comment by karuppiah7890** [comment]
Yup! I can help test the App, and develop very small stuff! And it's surprising you started out this App just to learn stuff !

**Comment by amilajack** [comment]
Also I'm super new to OSS: 

<img width="701" alt="screen shot 2016-10-09 at 10 35 51 pm" src="https://cloud.githubusercontent.com/assets/6374832/19227584/c6065114-8e70-11e6-9be6-9019b2f2fc56.png">

(about 5 months) 

So don't let this repo intimidate you!

**Comment by karuppiah7890** [comment]
Okay! Thanks for the encouragement! :smile:

**Comment by ZakariaRidouh** [comment]
see #182 😸

**Comment by amilajack** [comment]
Also would you guys like me to make a list of first-timer PRs?

**Comment by karuppiah7890** [comment]
Sure! It would be very useful for us and others too! And there's this Twitter bot that actually looks out for "first-timers-only" labels in GitHub and tweets it out! So put out the labels as "first-timers-only" so that more new contributors are able to see it! :smile: 

Here's the Twitter bot I spoke about : https://twitter.com/first_tmrs_only

And here's another Twitter account, a bot I believe : https://twitter.com/yourfirstpr . It will retweet if you tweet to @yourfirstpr about your project and the "first-timer-only" or "first-timer" labels and mentioning Js as the codebase.

**Comment by amilajack** [comment]
First-timer PR List!

https://github.com/amilajack/popcorn-time-desktop/issues/183

**Comment by amilajack** [comment]
Just tweeted them and added the label. Thanks for the suggestion!

**Comment by karuppiah7890** [comment]
:smile: And the first-timers-only bot has tweeted too !

![tweet](https://cloud.githubusercontent.com/assets/12808424/19228537/d3baa7e2-8ee3-11e6-9f16-20a6d7b895fa.png)
