### ISSUE TITLE
First-Timer PR List

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#183]
**SUPER** Important PR's that need to be made for `release-0.0.6-alpha`:

**1. End to End Tests for `ItemPage` container component**
Background: Right now, there aren't any tests to assert whether a season and episode can be selected and played. We need tests for checking if the displayed episodes actually update when a season is clicked.

Some pseudo-code:

``` js
await onSeasonClick()
expect(await checkIfEpisodesUpdated()).to.equal(true)
```

Advice: Wait for the `presentational-layer-refactoring` branch to be merged into `release-0.0.6-alpha` branch to avoid merge conflicts and naming collisions. Use the existing end-to-end tests (in `e2e.spec.js`) as an example and the webdriver.io and spectron docs for reference.

Related bugs:
- https://github.com/amilajack/popcorn-time-desktop/issues/179
- https://github.com/amilajack/popcorn-time-desktop/issues/180
- https://github.com/amilajack/popcorn-time-desktop/issues/163

**2. Dev: Deploy releases through Travis and Appveyor using Artifacts**
Background: This was take directly from the roadmap for `release-0.0.6-alpha` but I don't think this should require much work or background knowledge in JS. What we need is a way of automatically deploying releases to GitHub if both appveyor and travis builds succeed. Reference the [electron-builder](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts) documentation for steps on how to do this.

**3. Feature: Alert when new update available**
Background: This too was taken straight from the roadmap! It's probably one of the most important features planned for the next release. [I've already done some work for this](https://github.com/amilajack/popcorn-time-desktop/blob/release-0.0.6-alpha/app/components/home/Home.js#L12-L30). It just needs some testing and improved integration with the app.

**4. Dev: Increate compatibility with Flow, enable `tcomb`**
Background: Currently, the project doesn't fully take advantage of Flow. It doesn't use any flow definitions, which is terrible for developer experience. There are also a number of places where type definitions are not strict enough. I haven't looked into proper integration yet so I can't give much advice and background on this one. But I'm sure there are some good articles and documentation out there that explain the steps for this.

`tcomb` does runtime checks in development. Something like this:

``` js
function sayHi(name) {
  if (typeof name !== string) throw new Error('name is not a string')
}
```

It was temporarily disabled in the `.babelrc` because Flow isnt integrated enough to provide meaningful warnings. Enabling `tcomb` should follow improving Flow integration.

Related Issues:
- https://github.com/amilajack/popcorn-time-desktop/issues/154

**Comment by TushaarGVS** [comment]
I want to work on this project if you please!

**Comment by amilajack** [comment]
@TushaarGVS Great! I've just invited you to the gitter chat. I've just commented in the chat on how to contribute. Hope that helps! Let me know if you have any more questions.
