### ISSUE TITLE
PR: Migration to `themoviedb` from `trakt.tv`

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#185]
Due to trakt.tv [removing images from its api](https://apiblog.trakt.tv/trakt-api-images-56b43c356427#.lkhjkc10d), there will need to be a migration to an api endpoint that provides images with their api, namely `themoviedb`. A new `MetadataProvider` needs to be written for the new endpoint before the 31st, which is when trakt will official stop delivering images with their api :(

**Comment by ZakariaRidouh** [comment]
@karuppiah7890 are you sure that link is to an API? It just links to a Free Code Camp challenge.

**Comment by karuppiah7890** [comment]
Oops. Damn copy pasting.

**Comment by amilajack** [comment]
> Hey, is it necessary to rewrite the whole module ?

We're actually going to need to create a new MetadataProvider, which is pretty much rewriting the entire `TraktMetadataProvider`. Kind of annoying but its not very difficult. Won't require changing existing code. By default, the API won't use Trakt. It will use only `themoviedb`. The performance of fetching images for each item returned from trakt would be suboptimal and it would require changes to the existing architecture, which is pretty sound.

One benefit of this migration, besides having images in our app, is also improved search results and image quality of search results. Trakt's search api was so bad that we had to use [omdbapi](www.omdbapi.com) instead, but its image quality of their posters is terrible.

A couple downsides are that the images from `themoviedb` might not be compressed. One of the ways that we get performance improvements with this app is by using the smallest image sizes possible for large item lists (like the home page). Another significant downside to the api is that it doesnt return IMDBI ID's, which are essential for finding good torrents.

**Comment by karuppiah7890** [comment]
Well, if search results are good, then this should be good. And about the IMDB IDs, what do you mean by "finding good torrents" ? You mean good movies ?

**Comment by amilajack** [comment]
>  You mean good movies based on IMDB rating?

Each movie has an imdb id. That makes finding a movie really easy. Some of the `TorrentProvider`'s rely on imdb id's to fetch torrents with a lot of seeders/

**Comment by karuppiah7890** [comment]
Oh. Okay. 
I thought the movie name is enough.
I guess I will make a pet project to grab torrents and try out stuff.
