### ISSUE TITLE
Creation of `.github` directory

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#186]
@ZakariaRidouh Last comment on the GitHub templates. Promise!

Can we have something like this:
<img width="221" alt="screen shot 2016-10-11 at 10 35 56 am" src="https://cloud.githubusercontent.com/assets/6374832/19281327/a7f22f0c-8f9e-11e6-8497-606ce43b167f.png">

Its a pretty common convention and i think it can clean up our root dir a bit. Thanks! 💥

**Comment by ZakariaRidouh** [comment]
@amilajack Wait, im pretty sure it already exists. I made sure to put them into one like that 😸 

![image](https://cloud.githubusercontent.com/assets/11602629/19292010/c7b8167e-8fcd-11e6-803e-41075ca0ee44.png)

cheers! :star2:

**Comment by amilajack** [comment]
Oh nice! Should have checked before opening this 😂 thanks!
