### ISSUE TITLE
Discussion: switch to using Noto font

### ISSUE THREAD

**Issue by ZakariaRidouh** [amilajack/popcorn-time-desktop#188]
The great thing about using this font is that it supports many many languages (about 581 for the Noto sans IIRC) plus its made and supported by Google so we can bank on lots of improvements over time.

See https://www.google.com/get/noto/

Inspired by butterproject/butter-desktop#444

**Comment by amilajack** [comment]
Currently we're using the font in [our designs](https://github.com/amilajack/popcorn-time-desktop-design). For design related changes, we should design mockups and post them in the 'redesign' issue to get some feedback.

**Comment by amilajack** [comment]
Closing because discussion should be moved to https://github.com/amilajack/popcorn-time-desktop/issues/145
