### ISSUE TITLE
Clean up project root

### ISSUE THREAD

**Issue by ZakariaRidouh** [amilajack/popcorn-time-desktop#190]
Currently, the project root is littered with many files that could easily be moved into the same files, such as these webpack files
![screen shot 2016-10-13 at 9 33 35 pm](https://cloud.githubusercontent.com/assets/11602629/19376008/af8c89f0-918e-11e6-9614-982eaeb312f5.png)
and the babelrc file which can be put into the package.json IIRC

Willing to PR if everyone else is happy with it!
cheers 💥 😄

**Comment by amilajack** [comment]
How about adding support for this: https://github.com/kentcdodds/webpack-config-utils#usage

**Comment by amilajack** [comment]
Would make understanding our webpack config so much easier.
