### ISSUE TITLE
PR: Add initial Jest tests

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#198]

**Comment by ZakariaRidouh** [comment]
Is the project going to use Jest over Mocha now?

**Comment by amilajack** [comment]
I think we should use both. Mocha currently tests the API and e2e tests. Jest can check our react components specifically.

**Comment by onbjerg** [comment]
Seems a bit odd.

**Comment by amilajack** [comment]
Also I haven't used jest before so I'm not sure if its good at testing network requests. Also our tests are a couple hundred lines long so i'm not really sure if migrating our api tests to jest would be a good investment of our time,
