### ISSUE TITLE
Searching by actor, director, writer

### ISSUE THREAD

**Issue by amnchre** [amilajack/popcorn-time-desktop#220]
Merely a suggestion, as this was possible in the Community Edition at some point in time and now it doesn't. Also crediting actors and directors in the description would make this app perfect.
Thanks boys.

**Comment by amilajack** [comment]
@amnchre I dont actively maintain this project at the moment, although I do plan on revisiting this project and maintaining it some time in the future. Does this project still function correctly? Last time I tried it, it didn't work because of API endpoint changes

**Comment by amnchre** [comment]
I thought this was the official version but see now I was wrong. Not a problem. Haven't tried it myself.
