### ISSUE TITLE
Latest Alpha 0.0.7 -  app is empty  - no UI - no content

### ISSUE THREAD

**Issue by Draxler** [amilajack/popcorn-time-desktop#228]
Win7/64bit | latest version v0.0.7-alpha1
____________________________________________

After instalation = latest version v0.0.7-alpha1 ; app is completley emptey, without any UI at all and with no content.
______________________________________________________________________________________

v0.0.7-alpha1
|
![screenshot_1](https://user-images.githubusercontent.com/7681671/28065046-40aadaea-6637-11e7-9a87-24c7f6c7eed1.png)

___________________________________________________________________________________________

alpha 0.0.6 (if instal back older version = alpha 0.0.6 ; everything is back: UI + content)
|
![screenshot_2](https://user-images.githubusercontent.com/7681671/28064795-3e22beba-6636-11e7-86de-e445e8ca8375.png)
______________________________________________________________________________________________

Regards

**Comment by amilajack** [comment]
This is a build issue because of mdns. Will fix this today

**Comment by CHEF-KOCH** [comment]
Still not fixed.
