### ISSUE TITLE
DOT character

### ISSUE THREAD

**Issue by vaibhavpacharya** [amilajack/popcorn-time-desktop#233]
"Not rewriting GET /dist/bundle.js because the path includes a dot (.) character."
I keep getting this error along with 404 Not found error in the console.
Please help
![screenshot 45](https://user-images.githubusercontent.com/16417441/38461616-08bb9b38-3aa3-11e8-82a0-210776e1e3b2.png)

**Comment by vaibhavpacharya** [comment]
PS I have rewritten the bundle.js for main.entry.js as output file

**Comment by TriPSs** [comment]
@vaibhavpacharya Are all deps installed? Because there is a error that `node-sass` is not installed.

Ps: I don't think this project is very alive any more.
