### ISSUE TITLE
React navigating between 'shows' and 'movies' routes is slow

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#31]

**Comment by thangngoc89** [comment]
This is because you're doing the fetching on routes changing. Possible solution is removing the fetching from the component, process it with redux-thunk or redux-saga and then dispatch the result to component. This allows you to render a placeholder as well as caching the result for further use

**Comment by amilajack** [comment]
@thangngoc89 good idea! I'll look into this.

**Comment by amilajack** [comment]
The cache fixes this. ✨
