### ISSUE TITLE
Audio not playing for certain videos

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#35]
I've noticed that certain movies or tv shows do not play sound corrrectly. This may be because of the file format of certain torrents. Possible places of error: electron support for mkv, peerflix

**Comment by amilajack** [comment]
The opposite of this issue seems to happen as well: when playing torrents, the video will not play but the sound will:

Working Example: Game of thrones s06e05
NonWorking Video Example: Game of thrones s06e010

**Comment by thangngoc89** [comment]
This looks like a codec issue for me. I saw several videos like this, tried on multiple video player but no luck.

**Comment by amilajack** [comment]
Yup. This was fixed partially by WebChimera.js.
