### ISSUE TITLE
Move `npm run test-all` from precommit hook to prepush hook

### ISSUE THREAD

**Issue by thangngoc89** [amilajack/popcorn-time-desktop#52]
I commit a lot and this is pretty annoying to me. I think that you only need to run test before pushing to remote server since you can make a mess in a branch and then rebase it.

**Comment by amilajack** [comment]
This can be fixed with:

```bash
git commit --all --no-verify

// or if you use gca
gca --no-verify
```

**Comment by thangngoc89** [comment]
Thanks
