### ISSUE TITLE
tv shows runtime broken

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#577]
Runtime is always showing 0 only for tv shows. Works fine for movies.

<img width="382" alt="Screen Shot 2019-04-21 at 3 02 54 PM" src="https://user-images.githubusercontent.com/6374832/56476072-a037a380-6446-11e9-95cd-764da77d65b2.png">

**Comment by pedroabreu** [comment]
This is fixed on #573
