### ISSUE TITLE
Migrate  `Butter`, `Player`, `Config`, and `Torrent` to main process

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#76]
When using this method, show torrents are almost always guaranteed but it retrieving complete show torrents uses a significant amount of memory and causes the main process to drop frames.

Possible solutions include
- moving this to a separate thread using `childProcess`
- Using electron's 'main process' and send messages through IPC

**Comment by amilajack** [comment]
Update: the entire renderer process slows to a crawl when `webtorrent` runs on it. `webtorrent` needs to be moved to electron's `main` process.

**Comment by vzamanillo** [comment]
Another interesting option, [hidden browser windows](http://blog.smith-kyle.com/background-processes-in-electron/), it is easy to setup via [electron-process](https://www.npmjs.com/package/electron-process) module.
