### ISSUE TITLE
Torrent playback slows down entire network

### ISSUE THREAD

**Issue by amilajack** [amilajack/popcorn-time-desktop#95]
This can be solved by limiting the maximum number of connections that the torrent clients can make. Ideally, this would be configured by an `ENV` variable.

**Comment by ZakariaRidouh** [comment]
We could also have it change over time depending on the network speed (from the network module).

**Comment by amilajack** [comment]
It doesnt have to be that strict. Just check if it returns a number

```js
expect(speed).to.be.a('number')
```

**Comment by amilajack** [comment]
Should be enough

**Comment by amilajack** [comment]
Fixed
